import { CompanyTitle, DescriptionWrapper,
         ExperienceItem,
         FooterDescription,
         FooterStyled,
         GitHubImage,
         HeaderContainer,
         HeaderLogo,
         HeaderTitle,
         HeaderWrapper,
         HomePageContainer,
         IntroContainer,
         IntroTitle,
         LanguageList,
         LanguageListItem,
         LanguagesSpan,
         LanguagesSpanIcon,
         LanguagesWrapper, ListItem, 
         ResumeContainer, 
         RolTitle, 
         RolTitleContainer, 
         SkillsContainer, 
         SkillsItem, 
         SkillsList, 
         SkillsListContainer, 
         SkillsTitle, 
         ThirdIcons,
         TimePeriod,
         WorkExperienceContainer,
         WorkExperienceContent,
         WorkExperienceDescription,
         WorkExperienceWrapper} from "./style.components";
         
/**Jose-profile web - version 6.02 - style components > index - 
 * Features:
 * 
 *      --> Importing and exporting 'HomePageContainer'.
 * 
 * Notes: All these are clean files in data, directory and 
 * files
 */

export { IntroContainer,
         IntroTitle,
         LanguagesWrapper,
         DescriptionWrapper, 
         LanguageList,
         LanguagesSpanIcon,
         HeaderWrapper,
         HeaderContainer,
         HeaderTitle,
         HeaderLogo,
         FooterStyled,
         ThirdIcons,
         FooterDescription,
         GitHubImage,
         ResumeContainer,
         SkillsContainer,
         SkillsTitle,
         SkillsList,
         SkillsListContainer,
         SkillsItem,
         WorkExperienceWrapper,
         WorkExperienceContainer,
         WorkExperienceDescription,
         RolTitleContainer,
         RolTitle,
         CompanyTitle,
         WorkExperienceContent,
         TimePeriod,
         ExperienceItem,
         HomePageContainer,
         LanguageListItem, ListItem, LanguagesSpan }